# Generated by Django 3.2.7 on 2021-10-22 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nombre')),
                ('pob', models.IntegerField(default=0, verbose_name='Población')),
            ],
        ),
        migrations.CreateModel(
            name='Protectora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direc', models.CharField(max_length=200, verbose_name='Direccion')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcogeM_app.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ape', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=9)),
                ('tel', models.IntegerField(blank=True, null=True, verbose_name='Teléfono')),
                ('exp', models.TextField(verbose_name='Experiencia con animales')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descrip', models.TextField(verbose_name='Descripción')),
                ('tipo', models.CharField(blank=True, choices=[('p', 'Perro'), ('g', 'Gato'), ('h', 'Huron'), ('c', 'Conejo')], default='p', max_length=1, verbose_name='Tipo')),
                ('edad', models.IntegerField(default=0, null=True, verbose_name='Edad')),
                ('protectora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcogeM_app.protectora')),
            ],
        ),
    ]
