# Generated by Django 3.2.7 on 2021-10-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcogeM_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectora',
            name='cod',
            field=models.DecimalField(decimal_places=0, default=11000, max_digits=5, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='descrip',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='exp',
            field=models.TextField(verbose_name='Experiencia con animales'),
        ),
    ]
