# Generated by Django 3.2.7 on 2021-10-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcogeM_app', '0002_alter_perfil_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name_plural': 'Animales'},
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='protectora',
            options={'verbose_name_plural': 'Protectoras'},
        ),
    ]
