# Generated by Django 3.2.7 on 2021-10-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcogeM_app', '0002_auto_20211006_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='protectora',
            name='cod',
        ),
        migrations.AddField(
            model_name='animal',
            name='edad',
            field=models.IntegerField(default=0, verbose_name='Edad'),
        ),
    ]
