# Generated by Django 3.2.7 on 2022-02-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcogeM_app', '0004_animal_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Imagen'),
        ),
    ]
