# Generated by Django 3.2.7 on 2022-02-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcogeM_app', '0005_alter_animal_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='adoptado',
            field=models.BooleanField(default=False),
        ),
    ]
