# Generated by Django 3.2.7 on 2022-03-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcogeM_app', '0006_animal_adoptado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='fotociu',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='protectora',
            name='fotopro',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Imagen'),
        ),
    ]
